name: On pull requests

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --force

      - name: Run Biome Check
        run: npx biome check

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --force

      - name: Build Next.js Application
        run: npm run build

  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://gato:gato@localhost:5433/gatodb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --force

      - name: launch docker
        run: docker compose up test-db -d

      - name: test setup
        run: sleep 10 && npm run db:push:test

      - name: Run Vitest
        run: npm run test
